language: go

go:
  - 1.12.x
  - master

env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

git:
  depth: 1

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled

after_success:
  - bash <(curl -s https://codecov.io/bash)